sudo: required
services:
 - docker

before_install:
 - docker build -t pizdebski/complex-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true pizdebski/complex-test npm test

after_success:
 - docker build -t pizdebski/multi-client ./client 
 - docker build -t pizdebski/multi-nginx ./nginx
 - docker build -t pizdebski/multi-server ./server
 - docker build -t pizdebski/multi-worker ./worker
 
 # docker hub
 - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
 - docker push pizdebski/multi-worker
 - docker push pizdebski/multi-client
 - docker push pizdebski/multi-nginx
 - docker push pizdebski/multi-server

deploy:
  edge: true
  provider: elasticbeanstalk
  region: "eu-central-1"
  app: "MultiDocker2"
  env: "MultiDocker-env-2"
  bucket_name: "elasticbeanstalk-eu-central-1-446518935327"
  bucket_path: "MultiDocker2"
  on:
   branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
