sudo: required
services:
 - docker

before_install:
 - docker build -t pizdebski/complex-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true pizdebski/react-test npm test

after_success:
 - docker build -t pizdebski/multi-client ./client 
 - docker build -t pizdebski/multi-nginx ./nginx
 - docker build -t pizdebski/multi-server ./server
 - docker build -t pizdebski/multi-workter ./worker
 # docker hub
 - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
 - docker push pizdebski/multi-client
 - docker push pizdebski/multi-nginx
 - docker push pizdebski/multi-server
 - docker push pizdebski/multi-worker
